# Generated by Django 2.2.3 on 2019-07-19 15:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_answerstar_questionstar'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answerstars',
            field=models.ManyToManyField(related_name='answerstars', through='core.AnswerStar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='questionstars',
            field=models.ManyToManyField(related_name='questionstars', through='core.QuestionStar', to=settings.AUTH_USER_MODEL),
        ),
    ]
